#index:
#    path: /
#    controller: App\Controller\DefaultController::index
schema:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'schema.html.twig'
